output_dir="../HTML"
title="Endless Battle"
# Uncomment below line if you want to use as test purpose, and make sure to recomment after testing and back to your base url.
#base_url="/"
base_url="https://harrymkt.github.io/endless-battle"
theme="zluinav"
author="Harry Min Khant"
feed_filenames = ["rss.xml"]
compile_sass = false
build_search_index = false
default_language="en"
[slugify]
paths = "on"
taxonomies = "off"
anchors = "off"
[extra]
nav=[
{name="Home", url="/.l./"},
{name="Documentation", url="/.l./docs/"},
{name="Blog", url="/blog/"},
{name="Contributing", url="/.l./contribute/"},
{name="Contributors and credits", url="/.l./contributors/"},
{name="To Do List", url="/.l./to-do-list/"}
]